### ISSUE TITLE
Feature Request:  weather alerts

### ISSUE THREAD

**Issue by JtwoA** [thepcg/weathermon#2]
Create a template that simply has the date and time present but, in the event of an alert, appends this information into the template.  In the absence of an alert it continues to provide just date and time info.

STUDIO only loads/schedules once per day and the playlist is not a living document but set at 2330 ET each prior night hence the need for an always-present file.  The file can be updated behind the scenes up until broadcast but cannot be added on the fly if it was not on the playlist to begin with.

**Comment by JtwoA** [comment]
The bottom line to this one is that STUDIO must see a file (let's call it ALERT.mp3) every night at 2330 ET when it schedules.  If it doesn't, no matter what happens during the scheduled period it will not be added.

But....

If you always have a file named ALERT.mp3 present and accounted for (even if it plays back nothing more than "From the WTAF Weather Center" and then hands off to the TODAY.mp3) it can be updated over and over during the day without issue.

So... on each hourly pull if an alert suddenly pops in then the template for this would be then appended with the alert verbiage and field data.

Make sense?  (It does to me 'cause I live with it lol)

**Comment by thepcg** [comment]
So in the event of an alert during a request, you would like to have the alert inserted into the output file you're using for the full forecast? Or a separate output file?

**Comment by JtwoA** [comment]
Well, if it's Christmas, it would be preferred to have it appended to the top to the output file for the full forecast.  But if it needs to be a sep file then so be it (keeping in mind the original comments).

**Comment by JtwoA** [comment]
http://www.wunderground.com/weather/api/d/docs?d=data/index

As we discussed briefly.

The free API limits are:
- 500 calls/day
- 10 calls/minute

**Comment by JtwoA** [comment]
Any movement on this request?

**Comment by JtwoA** [comment]
<nudge>

**Comment by JtwoA** [comment]
Closing this as DarkSky contains this data.
