### ISSUE TITLE
Feature Request:  schedule use of templates

### ISSUE THREAD

**Issue by JtwoA** [thepcg/weathermon#3]
TODAY
0000 ET - 1659 ET

TONIGHT
1700 ET - 2159 ET

TOMORROW
2200 ET - 2359 ET

**Comment by thepcg** [comment]
Hello GWP1, I'm going to need a little more detail to review this request. Are you looking for the program to output three different files at three different times? If not, could you please clarify what you're looking for the application to do with this schedule?

**Comment by JtwoA** [comment]
The idea here is to have output_today.txt output during the TODAY hours, output_tonight.txt during the TONIGHT hours and an additional output_tomorrow.txt (optional atm) output during the TOMORROW hours.

But... here's the catch:  STUDIO doesn't have specific daytime and nighttime clocks for the most part.  Sure, during the workweek it has workday and evening but beyond that the weekend doesn't have anything but a weekend clock so I can't just say "this clock uses output_today.txt now and output_tonight.txt later."

I'm open to suggestions.  The two templates have different verbiage, obviously.  Thoughts?

**Comment by JtwoA** [comment]
Close this.

I figured out if I create a scheduled task that runs a batch file that
grabs the output_tonight.txt and renames it output_today.txt and schedule
it to run every day once at 1715, 1815, 1915, 2015, 2115, 2215, and 2315 ET
it takes care of it.
