### ISSUE TITLE
local.time minutes is not respecting new phonetic rules

### ISSUE THREAD

**Issue by thepcg** [thepcg/weathermon#6]
local.time minutes is not respecting new phonetic rules. 12:01pm is being read as 12. 1pm.

**Comment by thepcg** [comment]
This issue has been addressed in the latest build.

**Comment by JtwoA** [comment]
This is from five minutes ago.  We'll see how it likes the top of the hour
but it sounds a LOT better.

**Comment by JtwoA** [comment]
Here's from top of the hour and five minutes later.  Nice.
